# Linear Algebra for CpE
## Laboratory 6 : Matrices

Now that you have a fundamental knowledge about vector representations, we'll try to look into greater dimensions.

### Objectives
At the end of this activity you will be able to:
1. Be familiar with matrices and their relation to linear equations.
2. Perform basic matrix operations.
3. Program and translate matrix equations and operations using Python.

# Discussion

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

### Matrices

The notation and use of matrices is probably one of the fundamentals of modern computing. Matrices are also handy representations of complex equations or multiple inter-related equations from 2-dimensional equations to even hundreds and thousands of them.

Let's say for example you have $A$ and $B$ as system of equation.

$$
A = \left\{
    \begin{array}\\
        x + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\\
        x+y+z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right. $$

We could see that $A$ is a system of 2 equations with 2 parameters. While $B$ is a system of 3 equations with 3 parameters. We can represent them as matrices as:

$$
A=\begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix}
$$

So assuming that you already discussed the fundamental representation of matrices, their types, and operations. We'll proceed in doing them in here in Python.

### Declaring Matrices

Just like our previous laboratory activity, we'll represent system of linear equations as a matrix. The entities or numbers in matrices are called the elements of a matrix. These elements are arranged and ordered in rows and columns which form the list/array-like structure of matrices. And just like arrays, these elements are indexed according to their position with respect to their rows and columns. This can be reprsented just like the equation below. Whereas $A$ is a matrix consisting of elements denoted by $a_{i,j}$. Denoted by $i$ is the number of rows in the matrix while $j$ stands for the number of columns.<br>
Do note that the $size$ of a matrix is $i\times j$.

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$

We already gone over some of the types of matrices as vectors but we'll further discuss them in this laboratory activity. Since you already know how to describe vectors using <b>shape</b>, <b>dimensions</b> and <b>size</b> attributes, we'll use them to analyze these matrices.

In [ ]:
## Since we'll keep on describing matrices. Let's make a function.
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [ ]:
## Declaring a 2 x 2 matrix
A = np.array([
    [1, 2],
    [3, 1]
])
describe_mat(A)

In [ ]:
G = np.array([
    [1,1],
    [2,2]
])
describe_mat(G)

In [ ]:
## Declaring a 3 x 2 matrix
B = np.array([
    [8, 2],
    [5, 4],
    [1, 1]
])
describe_mat(B)

In [ ]:
H = np.array([1,2,3,4,5])
describe_mat(H)

## Categorizing Matrices

There are several ways of classifying matrices. Once could be according to their <b>shape</b> and another is according to their <b>element values</b>. We'll try to go through them.

### According to shape

#### Row and Column Matrices

Row and column matrices are common in vector and matrix computations. They can also represent row and column spaces of a bigger vector space. Row and column matrices are represented by a single column or single row. So with that being, the shape of row matrices would be $1 \times j$ and column matrices would be $i \times 1$.

In [ ]:
## Declaring a Row Matrix

row_mat_1D = np.array([
    1, 3, 2
]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row matrix.
row_mat_2D = np.array([
    [1,2,3]
]) ## this is a 2-D Matrix with a shape of (1,3)
describe_mat(row_mat_1D)
describe_mat(row_mat_2D)

In [ ]:
## Declaring a Column Matrix
col_mat = np.array([
    [1],
    [2],
    [5]
]) ## this is a 2-D Matrix with a shape of (3,1)
describe_mat(col_mat)

#### Square Matrices

Square matrices are matrices that have the same row and column sizes. We could say a matrix is square if $i = j$. We can tweak our matrix descriptor function to determine square matrices.

In [ ]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [ ]:
square_mat = np.array([
    [1,2,5],
    [3,3,8],
    [6,1,2]
])

non_square_mat = np.array([
    [1,2,5],
    [3,3,8]
])
describe_mat(square_mat)
describe_mat(non_square_mat)

### According to element values

#### Null Matrix

A Null Matrix is a matrix that has no elements. It is always a subspace of any vector or matrix.

In [ ]:
def describe_mat(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')

In [ ]:
null_mat = np.array([])
describe_mat(null_mat)

#### Zero Matrix

A zero matrix can be any rectangular matrix but with all elements having a value of 0.

In [ ]:
zero_mat_row = np.zeros((1,2))
zero_mat_sqr = np.zeros((2,2))
zero_mat_rct = np.zeros((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')

#### Ones Matrix

A ones matrix, just like the zero matrix, can be any rectangular matrix but all of its elements are 1s instead of 0s.

In [ ]:
ones_mat_row = np.ones((1,2))
ones_mat_sqr = np.ones((2,2))
ones_mat_rct = np.ones((3,2))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

#### Diagonal Matrix

A diagonal matrix is a square matrix that has values only at the diagonal of the matrix. 

In [ ]:
np.array([
    [2,0,0],
    [0,3,0],
    [0,0,5]
])
# a[1,1], a[2,2], a[3,3], ... a[n-1,n-1]

In [ ]:
d = np.diag([2,3,5,7])
np.diag(d).shape == d.shape[0] == d.shape[1]


#### Identity Matrix

An identity matrix is a special diagonal matrix in which the values at the diagonal are ones.

In [ ]:
np.eye(5)

In [ ]:
np.identity(5)

#### Upper Triangular Matrix

An upper triangular matrix is a matrix that has no values below the diagonal. 

In [ ]:
np.array([
    [1,2,3],
    [0,3,1],
    [0,0,5]
])

#### Lower Triangular Matrix

A lower triangular matrix is a matrix that has no values above the diagonal.

In [ ]:
np.array([
    [1,0,0],
    [5,3,0],
    [7,8,5]
])

## Practice

1. Given the linear combination below, try to create a corresponding matrix representing it.

$$\theta = 5x + 3y - z$$

In [ ]:
theta = np.array([
              [5,3,-1],
])
describe_mat(theta)

2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.

$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$

In [ ]:
number2_mat = np.array([
             [1,2,1],
             [0,4,-1],
             [0,0,10]
])
describe_mat(number2_mat)

3. Given the matrix below, express it as a linear combination in a markdown.

In [ ]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])


$$G = 
\begin{bmatrix}1&7&8\\2&2&2\\4&6&7
\end{bmatrix}$$

$$G=\left\{\begin{array} 1g_1+7g_2+8g_3 \\2g_1+2g_2+2g_3\\4g_1+6g_2+7g_3
\end{array}\right.$$

4. Given the matrix below, display the output as a LaTeX makdown also express it as a system of linear combinations.

In [ ]:
H = np.tril(G)
H

$$
H = \left\{\begin{array}
1x_1\\
2x_1+ 2y_2\\
4x_1+ 6y_2 +7z_3
\end{array}\right.
$$

$$\begin{equation*}
H = 
\begin{bmatrix}
1 & 0 & 0 \\
2 & 2 & 0 \\
4 & 6 & 7
\end{bmatrix}
\end{equation*}$$

# Matrix Algebra

### Addition

In [69]:
A = np.array([
    [1,2],
    [2,3],
    [4,1]
])
B = np.array([
    [2,2],
    [0,0],
    [1,1]
])
A+B



array([[3, 4],
       [2, 3],
       [5, 2]])

In [70]:
2+A ##Broadcasting
# 2*np.ones(A.shape)+A

array([[3, 4],
       [4, 5],
       [6, 3]])

### Subtraction

In [71]:
A-B

array([[-1,  0],
       [ 2,  3],
       [ 3,  0]])

In [72]:
3-B == 3*np.ones(B.shape)-B

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

### Element-wise Multiplication

In [ ]:
A*B
np.multiply(A,B)

In [ ]:
2*A

In [ ]:
alpha=10**-10
A/(alpha+B)

In [ ]:
np.add(A,B)

## Activity

### Task 1

Create a function named `mat_desc()` that througouhly describes a matrix, it should: <br>
1. Displays the shape, size, and rank of the matrix. <br>
2. Displays whether the matrix is square or non-square. <br>
3. Displays whether the matrix is an empty matrix. <br>
4. Displays if the matrix is an identity, ones, or zeros matrix <br>
   
Use 5 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [2]:
def mat_desc(matrix):
    if matrix.size > 0:
        if matrix.ndim == 2 and matrix.shape[0] == matrix.shape[1]:
            is_zeros = True if np.sum(matrix) == 0 else False
            is_ones = True if np.sum(matrix) == matrix.shape[0]*matrix.shape[1] else False 
            is_square = True if matrix.shape[0] == matrix.shape[1] else False 
            is_diagonal = True if np.allclose(matrix, np.diag(np.diag(matrix))) == True and is_zeros == False else False
            is_upper_diagonal = True if np.allclose(matrix, np.triu(matrix)) == True and is_zeros == False else False
            is_lower_diagonal = True if np.allclose(matrix, np.tril(matrix)) == True and is_zeros == False else False
            print("Matrix:\n",matrix)
            print("Shape:",matrix.shape)
            print("Rank: ",matrix.ndim)
            print("Is Square:        ",is_square)
            print("Is Ones:          ",is_ones)
            print("Is Zeros:         ",is_zeros)
            print("Is Diagonal:      ",is_diagonal)
            print("Is Upper Diagonal:",is_upper_diagonal)
            print("Is Lower Diagonal:",is_lower_diagonal)
        else:
            print("Matrix:\n",matrix)
            print("Shape:",matrix.shape)
            print("Rank: ",matrix.ndim)
            print("Is Square:         False")
            print("Is Ones:           False ")
            print("Is Zeros:          False")
            print("Is Diagonal:       False")
            print("Is Upper Diagonal: False")
            print("Is Lower Diagonal: False")
    else:
        print('Matrix is Null')

In [3]:
A = np.array([
    [1,1,1,1],
    [0,1,1,1],
    [0,0,1,1],
    [0,0,0,1]
])
B = np.zeros((4,4))
C = np.array([
    [1,0,0,0],
    [1,2,0,0],
    [1,2,3,0],
    [1,2,3,4]
])
D = np.array([
    [1,2,3,4,5],
    [1,2,3,4,5],
    [1,2,3,4,5]
])
E = np.array([
])

In [10]:
mat_desc(E)

Matrix is Null


### Task 2

Create a function named `mat_operations()` that takes in two matrices or scalars a input parameters it should:<br>
 1. Display the description of each matrix, if the parameter is a scalar it tells that it is a scalar rather than describing it as a matrix.
 2. Determines if the matrices are viable for operation and returns your own error message if they are not viable.
 3. Returns the sum of the matrices.
 4. Returns the differen of the matrices.
 5. Returns the element-wise multiplication of the matrices.
 6. Returns the element-wise division of the matrices.

Use 5 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [14]:
def mat_operations(num1,num2):
    if isinstance(num1,np.ndarray) and isinstance(num2,np.ndarray):
        print(f"Shape of the First Argument:{num1.shape}\nShape of the Second Argument:{num2.shape}")
        print(f"\nRank of the First Argument: {num1.ndim}\nRank of the Second Argument: {num2.ndim}")
        
        if num1.shape == num2.shape:
            print("\nSum of Matrices: \n",num1+num2)
            print("\nProduct of Matrices: \n",num1-num2)
            print("\nMultiplication of Matrices: \n",num1*num2)
            print("\nDivision of Matrices: \n",num1/(num2+10**-10))
        else: print(f"\nMatrix Operations are Impossible because Matrix Shapes are Not Equal. ")
    else:
        print("One or Two arument is scalar")
        print("\nBrodcasting Sum of Matrices: \n",num1+num2)
        print("\nBrodcasting Product of Matrices: \n",num1-num2)
        print("\nScalar Multiplication of Matrices: \n",num1*num2)
        print("\nBrodcasting Division of Matrices: \n",num1/(num2+10**-10))
        

In [15]:
A = np.ones((4,4))
B = np.zeros((4,4))
C = np.array([
    [1,2,3,4],
    [1,2,3,4],
    [1,2,3,4],
    [1,2,3,4]
])
D = np.array([
    [1,2,3,4,5],
    [1,2,3,4,5],
    [1,2,3,4,5]
])
E = np.ones((69,420,69))
F = 1

In [18]:
mat_operations(F,C)

One or Two arument is scalar

Brodcasting Sum of Matrices: 
 [[2 3 4 5]
 [2 3 4 5]
 [2 3 4 5]
 [2 3 4 5]]

Brodcasting Product of Matrices: 
 [[ 0 -1 -2 -3]
 [ 0 -1 -2 -3]
 [ 0 -1 -2 -3]
 [ 0 -1 -2 -3]]

Scalar Multiplication of Matrices: 
 [[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]

Brodcasting Division of Matrices: 
 [[1.         0.5        0.33333333 0.25      ]
 [1.         0.5        0.33333333 0.25      ]
 [1.         0.5        0.33333333 0.25      ]
 [1.         0.5        0.33333333 0.25      ]]


## Conclusion

For your conclusion synthesize the concept and application of the laboratory. Briefly discuss what you have learned and achieved in this activity. Also answer the question: "how can matrix operations solve problems in agriculture?".